name: Build
on: 
  push:
    branches: [ main ]
    tags:
      - 'v*'

  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run make

    - name: Publish      
      run: npm run publish      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  